Repository GreenWiNit/backend, pull requests merged in 2025-07, with the labels that each got.

#62 feat: [#61] enum request param 공통 처리
  src/main/java/com/example/green/domain/file/controller/converter/StringToPurposeConverter.java
  src/main/java/com/example/green/domain/file/controller/docs/ImageUploadControllerDocs.java
  src/main/java/com/example/green/domain/file/domain/vo/Purpose.java
  src/main/java/com/example/green/global/config/web/StringToEnumConverterFactory.java
  src/main/java/com/example/green/global/config/web/WebConfig.java
  src/test/java/com/example/green/domain/file/controller/converter/StringToPurposeConverterTest.java
Labels: dev:feature

#70 test: [#69] 엑셀 통합 테스트 베이스 추가
  src/test/java/com/example/integration/common/BaseIntegrationTest.java
  src/test/java/com/example/integration/common/ExcelDownloadTestBase.java
  src/test/java/com/example/integration/common/ServiceIntegrationTest.java
  src/test/java/com/example/integration/config/TestBeanConfig.java
  src/test/java/com/example/integration/excel/ExcelDataMapperRegistryIntTest.java
  src/test/java/com/example/integration/excel/ExcelDownloaderIntTest.java
  src/test/java/com/example/integration/excel/TestExcelDataMapper.java
  src/test/java/com/example/integration/file/FileServiceIntTest.java
  src/test/java/com/example/integration/file/FileTestUtil.java
Labels: dev:test, run-integration-test

#76 feat: [#75] 배송지 관련 작업
  src/main/java/com/example/green/domain/pointshop/controller/DeliveryAddressController.java
  src/main/java/com/example/green/domain/pointshop/controller/docs/DeliveryAddressControllerDocs.java
  src/main/java/com/example/green/domain/pointshop/controller/dto/DeliveryAddressCreateDto.java
  src/main/java/com/example/green/domain/pointshop/controller/message/DeliveryAddressResponseMessage.java
  src/main/java/com/example/green/domain/pointshop/entity/delivery/DeliveryAddress.java
  src/main/java/com/example/green/domain/pointshop/entity/delivery/vo/Recipient.java
  src/main/java/com/example/green/domain/pointshop/exception/deliveryaddress/DeliveryAddressExceptionMessage.java
  src/main/java/com/example/green/domain/pointshop/repository/DeliveryAddressRepository.java
  src/main/java/com/example/green/domain/pointshop/service/DeliveryAddressService.java
  src/main/java/com/example/green/domain/pointshop/service/command/DeliveryAddressCreateCommand.java
  src/main/java/com/example/green/domain/pointshop/service/result/DeliveryResult.java
  src/test/java/com/example/green/domain/pointshop/controller/DeliveryAddressControllerTest.java
  src/test/java/com/example/green/domain/pointshop/controller/request/DeliveryAddressRequest.java
  src/test/java/com/example/green/domain/pointshop/entity/delivery/DeliveryAddressTest.java
  src/test/java/com/example/green/domain/pointshop/entity/delivery/vo/RecipientTest.java
  src/test/java/com/example/green/domain/pointshop/service/DeliveryAddressServiceTest.java
Labels: dev:feature

#80 feat: [#77] 메일 기반 휴대전화 인증
  build.gradle
  src/main/java/com/example/green/domain/auth/controller/PhoneVerificationController.java
  src/main/java/com/example/green/domain/auth/controller/dto/PhoneVerificationRequest.java
  src/main/java/com/example/green/domain/auth/controller/message/PhoneVerificationResponseMessage.java
  src/main/java/com/example/green/domain/auth/entity/verification/PhoneVerification.java
  src/main/java/com/example/green/domain/auth/entity/verification/TokenGenerator.java
  src/main/java/com/example/green/domain/auth/entity/verification/vo/Attempt.java
  src/main/java/com/example/green/domain/auth/entity/verification/vo/PhoneNumber.java
  src/main/java/com/example/green/domain/auth/entity/verification/vo/VerificationStatus.java
  src/main/java/com/example/green/domain/auth/exception/AuthException.java
  src/main/java/com/example/green/domain/auth/exception/PhoneExceptionMessage.java
  src/main/java/com/example/green/domain/auth/repository/PhoneVerificationRepository.java
  src/main/java/com/example/green/domain/auth/service/PhoneVerificationEmail.java
  src/main/java/com/example/green/domain/auth/service/PhoneVerificationService.java
  src/main/java/com/example/green/domain/auth/service/result/PhoneVerificationResult.java
  src/main/java/com/example/green/domain/auth/utils/RandomTokenGenerator.java
  src/main/java/com/example/green/global/config/TimeConfig.java
  src/main/java/com/example/green/infra/mail/GmailPhoneVerificationEmail.java
  src/main/java/com/example/green/infra/mail/ImapConfig.java
  src/main/java/com/example/green/infra/mail/ImapCredentials.java
  src/main/resources/application-mail.yml
  src/main/resources/application.yml
  src/test/java/com/example/green/domain/auth/controller/PhoneVerificationControllerTest.java
  src/test/java/com/example/green/domain/auth/entity/verification/PhoneVerificationTest.java
  src/test/java/com/example/green/domain/auth/entity/verification/vo/AttemptTest.java
  src/test/java/com/example/green/domain/auth/entity/verification/vo/PhoneNumberTest.java
  src/test/java/com/example/green/domain/auth/service/PhoneVerificationServiceTest.java
  src/test/java/com/example/green/domain/auth/utils/RandomTokenGeneratorTest.java
  src/test/resources/application.yml
Labels: dev:feature

#82 feat: [#72] 포인트 상점 이용자 쿼리 기능 구현
  src/main/java/com/example/green/domain/pointshop/controller/PointProductAdminController.java
  src/main/java/com/example/green/domain/pointshop/controller/PointProductController.java
  src/main/java/com/example/green/domain/pointshop/controller/docs/PointProductAdminControllerDocs.java
  src/main/java/com/example/green/domain/pointshop/controller/docs/PointProductControllerDocs.java
  src/main/java/com/example/green/domain/pointshop/controller/dto/PointProductDetail.java
  src/main/java/com/example/green/domain/pointshop/controller/dto/PointProductView.java
  src/main/java/com/example/green/domain/pointshop/controller/message/PointProductResponseMessage.java
  src/main/java/com/example/green/domain/pointshop/controller/query/PointProductQueryRepository.java
  src/main/java/com/example/green/infra/query/pointproduct/PointProductPredicates.java
  src/main/java/com/example/green/infra/query/pointproduct/PointProductProjections.java
  src/main/java/com/example/green/infra/query/pointproduct/PointProductQueryExecutor.java
  src/main/java/com/example/green/infra/query/pointproduct/PointProductQueryRepositoryImpl.java
  src/test/java/com/example/green/domain/pointshop/controller/PointProductAdminControllerTest.java
  src/test/java/com/example/green/domain/pointshop/controller/PointProductControllerTest.java
  src/test/java/com/example/green/domain/pointshop/controller/request/PointProductRequest.java
Labels: dev:feature

#85 feat: 포인트 상품 주문 기능 구현 (#83)
  src/main/java/com/example/green/domain/pointshop/controller/DeliveryAddressController.java
  src/main/java/com/example/green/domain/pointshop/controller/OrderController.java
  src/main/java/com/example/green/domain/pointshop/controller/dto/SingleOrderRequest.java
  src/main/java/com/example/green/domain/pointshop/controller/message/OrderResponseMessage.java
  src/main/java/com/example/green/domain/pointshop/entity/order/Order.java
  src/main/java/com/example/green/domain/pointshop/entity/order/vo/ItemSnapshot.java
  src/main/java/com/example/green/domain/pointshop/entity/point/vo/PointAmount.java
  src/main/java/com/example/green/domain/pointshop/exception/deliveryaddress/DeliveryAddressExceptionMessage.java
  src/main/java/com/example/green/domain/pointshop/exception/point/PointExceptionMessage.java
  src/main/java/com/example/green/domain/pointshop/repository/DeliveryAddressRepository.java
  src/main/java/com/example/green/domain/pointshop/repository/OrderRepository.java
  src/main/java/com/example/green/domain/pointshop/repository/PointTransactionRepository.java
  src/main/java/com/example/green/domain/pointshop/service/DeliveryAddressService.java
  src/main/java/com/example/green/domain/pointshop/service/OrderService.java
  src/main/java/com/example/green/domain/pointshop/service/PointProductService.java
  src/main/java/com/example/green/domain/pointshop/service/PointTransactionService.java
  src/main/java/com/example/green/domain/pointshop/service/command/SingleOrderCommand.java
  src/test/java/com/example/green/domain/pointshop/controller/DeliveryAddressControllerTest.java
  src/test/java/com/example/green/domain/pointshop/controller/OrderControllerTest.java
  src/test/java/com/example/green/domain/pointshop/entity/order/OrderItemTest.java
  src/test/java/com/example/green/domain/pointshop/entity/order/OrderTest.java
  src/test/java/com/example/green/domain/pointshop/service/DeliveryAddressServiceTest.java
  src/test/java/com/example/green/domain/pointshop/service/OrderServiceTest.java
  src/test/java/com/example/green/domain/pointshop/service/PointProductServiceTest.java
Labels: dev:feature

#88 feat: [#83] 다른 컨텍스트 포인트 지급 어댑터 구현
  src/main/java/com/example/green/domain/challenge/client/PointEarnClient.java
  src/main/java/com/example/green/domain/challenge/client/request/PointEarnRequest.java
  src/main/java/com/example/green/domain/member/client/PointEarnClient.java
  src/main/java/com/example/green/domain/point/adapter/PointTransactionAdaptor.java
  src/main/java/com/example/green/domain/point/entity/vo/PointAmount.java
  src/main/java/com/example/green/domain/point/service/PointTransactionService.java
  src/test/java/com/example/green/domain/point/adapter/PointTransactionAdaptorTest.java
  src/test/java/com/example/green/domain/point/service/PointTransactionServiceTest.java
Labels: dev:feature

#84 feat: [#37] OAuth2 & JWT 인증 시스템 및 로그인/로그아웃 기능 구현
  .gitignore
  build.gradle
  src/main/java/com/example/green/GreenApplication.java
  src/main/java/com/example/green/domain/auth/CustomSuccessHandler.java
  src/main/java/com/example/green/domain/auth/OAuth2FailureHandler.java
  src/main/java/com/example/green/domain/auth/constants/AuthConstants.java
  src/main/java/com/example/green/domain/auth/controller/AuthController.java
  src/main/java/com/example/green/domain/auth/dto/CustomOAuth2UserDto.java
  src/main/java/com/example/green/domain/auth/dto/GoogleResponseDto.java
  src/main/java/com/example/green/domain/auth/dto/OAuth2ResponseDto.java
  src/main/java/com/example/green/domain/auth/dto/OAuth2UserInfoDto.java
  src/main/java/com/example/green/domain/auth/dto/SignupRequestDto.java
  src/main/java/com/example/green/domain/auth/dto/TempTokenInfoDto.java
  src/main/java/com/example/green/domain/auth/dto/TokenResponseDto.java
  src/main/java/com/example/green/domain/auth/dto/UserDto.java
  src/main/java/com/example/green/domain/auth/enums/OAuth2Provider.java
  src/main/java/com/example/green/domain/auth/filter/JwtFilter.java
  src/main/java/com/example/green/domain/auth/model/entity/TokenManager.java
  src/main/java/com/example/green/domain/auth/model/vo/AccessToken.java
  src/main/java/com/example/green/domain/auth/model/vo/TempToken.java
  src/main/java/com/example/green/domain/auth/repository/RefreshTokenRepository.java
  src/main/java/com/example/green/domain/auth/service/AuthService.java
  src/main/java/com/example/green/domain/auth/service/CustomOAuth2UserService.java
  src/main/java/com/example/green/domain/auth/service/TokenCleanupEventListener.java
  src/main/java/com/example/green/domain/auth/service/TokenService.java
  src/main/java/com/example/green/domain/auth/utils/WebUtils.java
  src/main/java/com/example/green/domain/member/entity/Member.java
  src/main/java/com/example/green/domain/member/entity/enums/MemberRole.java
  src/main/java/com/example/green/domain/member/entity/vo/Profile.java
  src/main/java/com/example/green/domain/member/exception/MemberExceptionMessage.java
  src/main/java/com/example/green/domain/member/repository/MemberRepository.java
  src/main/java/com/example/green/domain/member/service/MemberService.java
  src/main/java/com/example/green/domain/member/util/MemberUtil.java
  src/main/java/com/example/green/global/config/SecurityConfig.java
  src/main/java/com/example/green/global/config/WebSecurityConfig.java
  src/main/java/com/example/green/global/error/exception/GlobalExceptionMessage.java
  src/main/java/com/example/green/global/security/PrincipalDetails.java
  src/main/java/com/example/green/global/security/SecurityUtil.java
  src/main/java/com/example/green/global/security/annotation/AdminApi.java
  src/main/java/com/example/green/global/security/annotation/AuthenticatedApi.java
  src/main/java/com/example/green/global/security/annotation/PublicApi.java
  src/main/resources/application-local.yml
  src/main/resources/application.yml
  src/main/resources/static/oauth-test.html
  src/main/resources/static/signup.html
  src/test/java/com/example/green/domain/member/MemberTest.java
  src/test/java/com/example/green/domain/member/util/MemberUtilTest.java
  src/test/java/com/example/integration/security/SecurityAnnotationTest.java
  src/test/resources/application.yml
Labels: dev:feature, run-integration-test

#109 fix: [#108] 백엔드 URL 설정 추가 및 CORS 허용 출처 확장
  src/main/java/com/example/green/global/config/SecurityConfig.java
  src/main/resources/application.yml
  src/test/java/com/example/integration/security/SecurityAnnotationTest.java
  src/test/resources/application.yml
Labels: bug, dev:fix

#110 fix: Swagger 설정에 백엔드 서버 URL 정확히 설정 및 로깅 기능 구현
  src/main/java/com/example/green/global/config/OpenApiConfig.java
  src/main/java/com/example/green/global/config/SecurityConfig.java
Labels: bug, dev:fix

#115 feat: 회원 포인트 조회 어댑터 구현(#114)
  src/main/java/com/example/green/domain/mypage/client/PointTotalGetClient.java
  src/main/java/com/example/green/domain/mypage/service/MypageFacadeService.java
  src/main/java/com/example/green/domain/point/adapter/PointTransactionAdaptor.java
  src/main/resources/application-mail.yml
  src/test/java/com/example/green/domain/point/adapter/PointTransactionAdaptorTest.java
Labels: dev:feature

#118 Feat/#89 회원 탈퇴 및 프로필 수정
  src/main/java/com/example/green/domain/auth/controller/AuthController.java
  src/main/java/com/example/green/domain/auth/service/AuthService.java
  src/main/java/com/example/green/domain/auth/service/CustomOAuth2UserService.java
  src/main/java/com/example/green/domain/auth/service/TokenService.java
  src/main/java/com/example/green/domain/file/domain/vo/Purpose.java
  src/main/java/com/example/green/domain/member/controller/MemberController.java
  src/main/java/com/example/green/domain/member/dto/ProfileUpdateRequestDto.java
  src/main/java/com/example/green/domain/member/dto/ProfileUpdateResponseDto.java
  src/main/java/com/example/green/domain/member/entity/Member.java
  src/main/java/com/example/green/domain/member/entity/vo/Profile.java
  src/main/java/com/example/green/domain/member/exception/MemberExceptionMessage.java
  src/main/java/com/example/green/domain/member/repository/MemberRepository.java
  src/main/java/com/example/green/domain/member/service/MemberService.java
  src/test/java/com/example/green/domain/auth/service/AuthServiceTest.java
  src/test/java/com/example/green/domain/member/MemberTest.java
  src/test/java/com/example/green/domain/member/controller/MemberControllerTest.java
  src/test/java/com/example/green/domain/member/entity/MemberTest.java
  src/test/java/com/example/green/domain/member/entity/vo/ProfileTest.java
  src/test/java/com/example/green/domain/member/service/MemberServiceTest.java
  src/test/java/com/example/green/global/security/annotation/SecurityAnnotationTest.java
  src/test/java/com/example/green/global/utils/UlidUtilsTest.java
  src/test/java/com/example/integration/auth/WithdrawMemberIntegrationTest.java
  src/test/java/com/example/integration/common/BaseEntityAuditingTest.java
Labels: dev:feature, run-integration-test

#128 refactor: [#106] race condition 해결
  build.gradle
  src/main/java/com/example/green/domain/point/entity/vo/PointAmount.java
  src/main/java/com/example/green/domain/point/repository/PointTransactionRepository.java
  src/main/java/com/example/green/domain/point/service/PointTransactionService.java
  src/main/java/com/example/green/domain/pointshop/controller/PointProductAdminController.java
  src/main/java/com/example/green/domain/pointshop/exception/point/PointExceptionMessage.java
  src/main/java/com/example/green/infra/adapter/PointTransactionAdaptor.java
  src/test/java/com/example/green/domain/point/adapter/PointTransactionAdaptorTest.java
  src/test/java/com/example/green/domain/point/service/PointTransactionServiceTest.java
  src/test/java/com/example/integration/common/BaseIntegrationTest.java
  src/test/java/com/example/integration/common/concurrency/ConcurrencyTestBuilder.java
  src/test/java/com/example/integration/common/concurrency/ConcurrencyTestConfig.java
  src/test/java/com/example/integration/common/concurrency/ConcurrencyTestExecutor.java
  src/test/java/com/example/integration/common/concurrency/ConcurrencyTestResult.java
  src/test/java/com/example/integration/common/concurrency/ConcurrencyTestTemplate.java
  src/test/java/com/example/integration/pointtransaction/PointTransactionRaceConditionTest.java
  src/test/resources/application.yml
  src/test/resources/logback-test.xml
Labels: run-integration-test

#141 chore : [#104] 사용자단 정보공유 수정
  src/main/java/com/example/green/domain/info/dto/user/InfoSearchResponseByUser.java
  src/main/java/com/example/green/domain/mypage/controller/MypageControllerDocs.java
Labels: dev:fix, chore

#142 feat: [#123] 개인/팀 챌린지 참여, 조회, 탈퇴 기능 구현
  src/main/java/com/example/green/domain/challenge/controller/ChallengeController.java
  src/main/java/com/example/green/domain/challenge/controller/docs/ChallengeControllerDocs.java
  src/main/java/com/example/green/domain/challenge/controller/dto/ChallengeDetailResponseDto.java
  src/main/java/com/example/green/domain/challenge/controller/dto/ChallengeListResponseDto.java
  src/main/java/com/example/green/domain/challenge/controller/dto/ChallengeParticipationStatus.java
  src/main/java/com/example/green/domain/challenge/controller/message/ChallengeResponseMessage.java
  src/main/java/com/example/green/domain/challenge/entity/TeamChallenge.java
  src/main/java/com/example/green/domain/challenge/entity/TeamChallengeGroup.java
  src/main/java/com/example/green/domain/challenge/enums/GroupStatus.java
  src/main/java/com/example/green/domain/challenge/exception/ChallengeExceptionMessage.java
  src/main/java/com/example/green/domain/challenge/repository/PersonalChallengeRepository.java
  src/main/java/com/example/green/domain/challenge/repository/PersonalChallengeRepositoryCustom.java
  src/main/java/com/example/green/domain/challenge/repository/PersonalChallengeRepositoryImpl.java
  src/main/java/com/example/green/domain/challenge/repository/TeamChallengeRepository.java
  src/main/java/com/example/green/domain/challenge/repository/TeamChallengeRepositoryCustom.java
  src/main/java/com/example/green/domain/challenge/repository/TeamChallengeRepositoryImpl.java
  src/main/java/com/example/green/domain/challenge/service/ChallengeService.java
  src/main/java/com/example/green/domain/challenge/utils/ChallengeCodeGenerator.java
  src/main/java/com/example/green/domain/challengecert/entity/TeamChallengeGroupParticipation.java
  src/main/java/com/example/green/domain/challengecert/entity/TeamChallengeParticipation.java
  src/main/java/com/example/green/domain/challengecert/repository/PersonalChallengeParticipationRepository.java
  src/main/java/com/example/green/domain/challengecert/repository/PersonalChallengeParticipationRepositoryCustom.java
  src/main/java/com/example/green/domain/challengecert/repository/PersonalChallengeParticipationRepositoryImpl.java
  src/main/java/com/example/green/domain/challengecert/repository/TeamChallengeGroupParticipationRepository.java
  src/main/java/com/example/green/domain/challengecert/repository/TeamChallengeParticipationRepository.java
  src/main/java/com/example/green/domain/challengecert/repository/TeamChallengeParticipationRepositoryCustom.java
  src/main/java/com/example/green/domain/challengecert/repository/TeamChallengeParticipationRepositoryImpl.java
  src/test/java/com/example/green/domain/challenge/entity/TeamChallengeGroupTest.java
  src/test/java/com/example/green/domain/challenge/entity/TeamChallengeTest.java
  src/test/java/com/example/green/domain/challenge/repository/TeamChallengeRepositoryTest.java
  src/test/java/com/example/green/domain/challenge/service/ChallengeServiceTest.java
  src/test/java/com/example/green/domain/challengecert/entity/TeamChallengeCertificationTest.java
  src/test/java/com/example/green/domain/challengecert/entity/TeamChallengeGroupParticipationTest.java
  src/test/java/com/example/green/domain/challengecert/entity/TeamChallengeParticipationTest.java
Labels: dev:feature, dev:fix, dev:test

#149 chore : [#148]사용자 정보조회 상세 이미지 경로 추가
  src/main/java/com/example/green/domain/info/dto/user/InfoDetailResponseByUser.java
  src/test/java/com/example/green/domain/info/controller/InfoControllerTest.java
Labels: chore

#146 feat: [#143] 팀챌린지 - 팀(그룹) 생성/수정/삭제/조회 및 참여
  src/main/java/com/example/green/domain/challenge/controller/TeamChallengeGroupController.java
  src/main/java/com/example/green/domain/challenge/controller/docs/TeamChallengeGroupControllerDocs.java
  src/main/java/com/example/green/domain/challenge/controller/dto/TeamChallengeGroupCreateRequestDto.java
  src/main/java/com/example/green/domain/challenge/controller/dto/TeamChallengeGroupDetailResponseDto.java
  src/main/java/com/example/green/domain/challenge/controller/dto/TeamChallengeGroupListResponseDto.java
  src/main/java/com/example/green/domain/challenge/controller/dto/TeamChallengeGroupUpdateRequestDto.java
  src/main/java/com/example/green/domain/challenge/controller/message/TeamChallengeGroupResponseMessage.java
  src/main/java/com/example/green/domain/challenge/entity/TeamChallengeGroup.java
  src/main/java/com/example/green/domain/challenge/entity/vo/GroupAddress.java
  src/main/java/com/example/green/domain/challenge/exception/ChallengeExceptionMessage.java
  src/main/java/com/example/green/domain/challenge/repository/TeamChallengeGroupRepository.java
  src/main/java/com/example/green/domain/challenge/repository/TeamChallengeGroupRepositoryCustom.java
  src/main/java/com/example/green/domain/challenge/repository/TeamChallengeGroupRepositoryImpl.java
  src/main/java/com/example/green/domain/challenge/service/TeamChallengeGroupService.java
  src/main/java/com/example/green/domain/challengecert/repository/TeamChallengeGroupParticipationRepository.java
  src/main/java/com/example/green/domain/challengecert/repository/TeamChallengeParticipationRepository.java
  src/test/java/com/example/green/domain/challenge/controller/TeamChallengeGroupControllerTest.java
  src/test/java/com/example/green/domain/challenge/entity/TeamChallengeGroupTest.java
  src/test/java/com/example/green/domain/challenge/entity/TeamChallengeTest.java
  src/test/java/com/example/green/domain/challenge/entity/vo/GroupAddressTest.java
  src/test/java/com/example/green/domain/challenge/service/ChallengeServiceTest.java
  src/test/java/com/example/green/domain/challenge/service/TeamChallengeGroupServiceTest.java
  src/test/java/com/example/green/domain/challengecert/entity/TeamChallengeCertificationTest.java
  src/test/java/com/example/green/domain/challengecert/entity/TeamChallengeGroupParticipationTest.java
  src/test/java/com/example/integration/challenge/TeamChallengeGroupRepositoryTest.java
Labels: dev:feature, dev:test

#155 feat: [#147] 챌린지 인증 - 회원용
  src/main/java/com/example/green/domain/challengecert/controller/ChallengeCertificationController.java
  src/main/java/com/example/green/domain/challengecert/controller/docs/ChallengeCertificationControllerDocs.java
  src/main/java/com/example/green/domain/challengecert/controller/message/ChallengeCertificationResponseMessage.java
  src/main/java/com/example/green/domain/challengecert/dto/ChallengeCertificationCreateRequestDto.java
  src/main/java/com/example/green/domain/challengecert/dto/ChallengeCertificationCreateResponseDto.java
  src/main/java/com/example/green/domain/challengecert/dto/ChallengeCertificationDetailResponseDto.java
  src/main/java/com/example/green/domain/challengecert/dto/ChallengeCertificationListResponseDto.java
  src/main/java/com/example/green/domain/challengecert/entity/BaseChallengeCertification.java
  src/main/java/com/example/green/domain/challengecert/entity/PersonalChallengeCertification.java
  src/main/java/com/example/green/domain/challengecert/entity/PersonalChallengeParticipation.java
  src/main/java/com/example/green/domain/challengecert/entity/TeamChallengeCertification.java
  src/main/java/com/example/green/domain/challengecert/entity/TeamChallengeGroupParticipation.java
  src/main/java/com/example/green/domain/challengecert/entity/TeamChallengeParticipation.java
  src/main/java/com/example/green/domain/challengecert/exception/ChallengeCertExceptionMessage.java
  src/main/java/com/example/green/domain/challengecert/repository/PersonalChallengeCertificationRepository.java
  src/main/java/com/example/green/domain/challengecert/repository/PersonalChallengeCertificationRepositoryCustom.java
  src/main/java/com/example/green/domain/challengecert/repository/PersonalChallengeCertificationRepositoryImpl.java
  src/main/java/com/example/green/domain/challengecert/repository/TeamChallengeCertificationRepository.java
  src/main/java/com/example/green/domain/challengecert/repository/TeamChallengeCertificationRepositoryCustom.java
  src/main/java/com/example/green/domain/challengecert/repository/TeamChallengeCertificationRepositoryImpl.java
  src/main/java/com/example/green/domain/challengecert/service/ChallengeCertificationService.java
  src/main/java/com/example/green/domain/file/domain/vo/Purpose.java
  src/test/java/com/example/green/domain/challengecert/controller/ChallengeCertificationControllerTest.java
  src/test/java/com/example/green/domain/challengecert/dto/ChallengeCertificationCreateRequestDtoTest.java
  src/test/java/com/example/green/domain/challengecert/dto/ChallengeCertificationCreateResponseDtoTest.java
  src/test/java/com/example/green/domain/challengecert/entity/PersonalChallengeCertificationTest.java
  src/test/java/com/example/green/domain/challengecert/entity/TeamChallengeCertificationTest.java
  src/test/java/com/example/green/domain/challengecert/repository/PersonalChallengeCertificationRepositoryImplTest.java
  src/test/java/com/example/green/domain/challengecert/repository/TeamChallengeCertificationRepositoryImplTest.java
  src/test/java/com/example/green/domain/challengecert/service/ChallengeCertificationServiceTest.java
Labels: dev:feature, dev:fix, dev:test

#160 refactor(auth): OAuth2 리다이렉트 URL 처리 방식 개선
  src/main/java/com/example/green/domain/auth/CustomSuccessHandler.java
Labels: bug

#162 feat: [#152] 관리자용 챌린지 관리 API 구현
  src/main/java/com/example/green/domain/challenge/controller/AdminChallengeController.java
  src/main/java/com/example/green/domain/challenge/controller/docs/AdminChallengeControllerDocs.java
  src/main/java/com/example/green/domain/challenge/controller/dto/admin/AdminChallengeCreateRequestDto.java
  src/main/java/com/example/green/domain/challenge/controller/dto/admin/AdminChallengeDetailResponseDto.java
  src/main/java/com/example/green/domain/challenge/controller/dto/admin/AdminChallengeDisplayStatusUpdateRequestDto.java
  src/main/java/com/example/green/domain/challenge/controller/dto/admin/AdminChallengeImageUpdateRequestDto.java
  src/main/java/com/example/green/domain/challenge/controller/dto/admin/AdminChallengeParticipantListResponseDto.java
  src/main/java/com/example/green/domain/challenge/controller/dto/admin/AdminChallengeUpdateRequestDto.java
  src/main/java/com/example/green/domain/challenge/controller/dto/admin/AdminPersonalChallengeListResponseDto.java
  src/main/java/com/example/green/domain/challenge/controller/dto/admin/AdminTeamChallengeGroupDetailResponseDto.java
  src/main/java/com/example/green/domain/challenge/controller/dto/admin/AdminTeamChallengeGroupListResponseDto.java
  src/main/java/com/example/green/domain/challenge/controller/dto/admin/AdminTeamChallengeListResponseDto.java
  src/main/java/com/example/green/domain/challenge/controller/message/AdminChallengeResponseMessage.java
  src/main/java/com/example/green/domain/challenge/entity/BaseChallenge.java
  src/main/java/com/example/green/domain/challenge/entity/PersonalChallenge.java
  src/main/java/com/example/green/domain/challenge/entity/TeamChallenge.java
  src/main/java/com/example/green/domain/challenge/enums/ChallengeDisplayStatus.java
  src/main/java/com/example/green/domain/challenge/enums/ChallengeType.java
  src/main/java/com/example/green/domain/challenge/repository/PersonalChallengeRepositoryCustom.java
  src/main/java/com/example/green/domain/challenge/repository/PersonalChallengeRepositoryImpl.java
  src/main/java/com/example/green/domain/challenge/repository/TeamChallengeGroupRepositoryCustom.java
  src/main/java/com/example/green/domain/challenge/repository/TeamChallengeGroupRepositoryImpl.java
  src/main/java/com/example/green/domain/challenge/repository/TeamChallengeRepositoryCustom.java
  src/main/java/com/example/green/domain/challenge/repository/TeamChallengeRepositoryImpl.java
  src/main/java/com/example/green/domain/challenge/service/AdminChallengeService.java
  src/main/java/com/example/green/domain/challengecert/repository/PersonalChallengeParticipationRepositoryCustom.java
  src/main/java/com/example/green/domain/challengecert/repository/PersonalChallengeParticipationRepositoryImpl.java
  src/main/java/com/example/green/domain/challengecert/repository/TeamChallengeGroupParticipationRepository.java
  src/main/java/com/example/green/domain/challengecert/repository/TeamChallengeParticipationRepositoryCustom.java
  src/main/java/com/example/green/domain/challengecert/repository/TeamChallengeParticipationRepositoryImpl.java
  src/main/java/com/example/green/domain/challengecert/repository/dao/ChallengeParticipantDao.java
  src/test/java/com/example/green/domain/challenge/controller/AdminChallengeControllerTest.java
  src/test/java/com/example/green/domain/challenge/service/AdminChallengeServiceTest.java
  src/test/java/com/example/green/domain/challenge/utils/CodeGeneratorTest.java
  src/test/java/com/example/integration/challenge/AdminChallengeIntegrationTest.java
  src/test/java/com/example/integration/challenge/TeamChallengeGroupRepositoryTest.java
Labels: dev:feature, dev:test, run-integration-test

#174 [Feat/#173] 닉네임 중복 검사 api 구현
  src/main/java/com/example/green/domain/auth/controller/AuthController.java
  src/main/java/com/example/green/domain/auth/service/AuthService.java
  src/main/java/com/example/green/domain/member/controller/MemberAdminController.java
  src/main/java/com/example/green/domain/member/controller/MemberController.java
  src/main/java/com/example/green/domain/member/controller/message/MemberResponseMessage.java
  src/main/java/com/example/green/domain/member/dto/NicknameCheckRequestDto.java
  src/main/java/com/example/green/domain/member/dto/NicknameCheckResponseDto.java
  src/main/java/com/example/green/domain/member/dto/ProfileUpdateRequestDto.java
  src/main/java/com/example/green/domain/member/entity/Member.java
  src/main/java/com/example/green/domain/member/entity/vo/Profile.java
  src/main/java/com/example/green/domain/member/exception/MemberExceptionMessage.java
  src/main/java/com/example/green/domain/member/repository/MemberRepository.java
  src/main/java/com/example/green/domain/member/service/MemberService.java
  src/test/java/com/example/green/domain/challenge/service/TeamChallengeGroupServiceTest.java
  src/test/java/com/example/green/domain/challengecert/repository/PersonalChallengeCertificationRepositoryImplTest.java
  src/test/java/com/example/green/domain/challengecert/repository/TeamChallengeCertificationRepositoryImplTest.java
  src/test/java/com/example/green/domain/member/controller/MemberControllerTest.java
  src/test/java/com/example/green/domain/member/service/MemberServiceTest.java
  src/test/java/com/example/integration/challenge/TeamChallengeGroupRepositoryTest.java
  src/test/java/com/example/integration/member/NicknameCheckIntegrationTest.java
Labels: dev:feature, run-integration-test

#179 [Feat/#164] 회원탈퇴시 회원 사유 입력 및 저장
  src/main/java/com/example/green/domain/auth/controller/AuthController.java
  src/main/java/com/example/green/domain/auth/controller/docs/AuthControllerDocs.java
  src/main/java/com/example/green/domain/auth/service/AuthService.java
  src/main/java/com/example/green/domain/auth/service/TokenService.java
  src/main/java/com/example/green/domain/member/controller/MemberAdminController.java
  src/main/java/com/example/green/domain/member/controller/MemberController.java
  src/main/java/com/example/green/domain/member/controller/docs/MemberControllerDocs.java
  src/main/java/com/example/green/domain/member/dto/WithdrawRequestDto.java
  src/main/java/com/example/green/domain/member/entity/WithdrawReason.java
  src/main/java/com/example/green/domain/member/entity/enums/WithdrawReasonType.java
  src/main/java/com/example/green/domain/member/exception/MemberExceptionMessage.java
  src/main/java/com/example/green/domain/member/repository/WithdrawReasonRepository.java
  src/main/java/com/example/green/domain/member/service/MemberService.java
  src/main/java/com/example/green/domain/member/service/WithdrawService.java
  src/test/java/com/example/green/domain/auth/service/AuthServiceTest.java
  src/test/java/com/example/green/domain/member/entity/WithdrawReasonTest.java
  src/test/java/com/example/green/domain/member/service/WithdrawServiceTest.java
  src/test/java/com/example/integration/auth/WithdrawMemberIntegrationTest.java
  src/test/java/com/example/integration/member/WithdrawMemberWithReasonIntegrationTest.java
Labels: dev:feature, run-integration-test
