Repository GreenWiNit/backend, pull requests merged in 2025-06, with the labels that each got.

#14 chore: [#8]swagger 파일 checkstyle 적용
  src/main/java/com/example/green/domain/example/controller/ExamplePostController.java
  src/main/java/com/example/green/domain/example/controller/ExamplePostControllerDocs.java
  src/main/java/com/example/green/domain/example/dto/PostResponse.java
  src/main/java/com/example/green/global/config/OpenApiConfig.java
  src/main/java/com/example/green/global/docs/ApiError400.java
  src/main/java/com/example/green/global/docs/ApiErrorStandard.java
Labels: chore

#17 test: [#12] 이미지 업로드 통합 테스트 작업
  build.gradle
  src/main/java/com/example/green/infra/storage/S3StorageHelper.java
  src/test/java/com/example/green/domain/TestEntityTest.java
  src/test/java/com/example/green/domain/file/utils/ImageValidatorTest.java
  src/test/java/com/example/green/dummy/ApiDummyController.java
  src/test/java/com/example/green/dummy/ErrorDummyController.java
  src/test/java/com/example/green/dummy/ValidationDto.java
  src/test/java/com/example/green/global/HealthControllerTest.java
  src/test/java/com/example/green/global/api/ApiTest.java
  src/test/java/com/example/green/global/error/ExceptionHandlerTest.java
  src/test/java/com/example/green/global/error/ValidationExceptionHandlerTest.java
  src/test/java/com/example/green/utils/IdUtilsTest.java
  src/test/java/com/example/green/utils/TimeUtilsTest.java
  src/test/java/com/example/green/utils/UriValidatorTest.java
  src/test/java/com/example/integration/common/ServiceIntegrationTest.java
  src/test/java/com/example/integration/config/MySqlTestContainerConfig.java
  src/test/java/com/example/integration/config/S3TestContainerConfig.java
  src/test/java/com/example/integration/file/FileServiceIntTest.java
  src/test/java/com/example/integration/file/FileTestUtil.java
  src/test/resources/application.yml
Labels: dev:test

#25 CICD: [#16] cd 파일에서 artifact를 copy할 때의 경로에서 "" 제거
  .github/workflows/deploy.yaml
  .github/workflows/integration-test.yaml
  .github/workflows/pr-check.yaml
Labels: archi:DevOps

#26 cicd: [#16] cd 내부 job: copy artifact 할 때, .env와 jar파일 생성된 위치를 명확히 선언
  .github/workflows/deploy.yaml
Labels: archi:DevOps, run-integration-test

#29 refactor:[#28] bean validation 메세지 포함하도록 수정
  src/main/java/com/example/green/global/error/GlobalExceptionHandler.java
  src/main/java/com/example/green/global/error/dto/DetailedExceptionResponse.java
  src/main/java/com/example/green/global/error/dto/ExceptionResponse.java
  src/test/java/com/example/green/global/error/ValidationExceptionHandlerTest.java
Labels: enhancement

#36 feat: [#33] 이미지 업로드 컨트롤러 구현 및 리팩터링
  src/main/java/com/example/green/domain/file/controller/ImageUploadController.java
  src/main/java/com/example/green/domain/file/controller/converter/StringToPurposeConverter.java
  src/main/java/com/example/green/domain/file/controller/docs/ImageUploadControllerDocs.java
  src/main/java/com/example/green/domain/file/controller/message/ImageResponseMessage.java
  src/main/java/com/example/green/domain/file/domain/vo/Purpose.java
  src/main/java/com/example/green/domain/file/exception/FileExceptionMessage.java
  src/main/java/com/example/green/domain/file/service/FileService.java
  src/main/java/com/example/green/domain/file/service/StorageHelper.java
  src/main/java/com/example/green/infra/storage/S3StorageHelper.java
  src/test/java/com/example/green/domain/file/controller/ImageUploadControllerTest.java
  src/test/java/com/example/green/domain/file/controller/converter/StringToPurposeConverterTest.java
  src/test/java/com/example/green/domain/file/service/FileServiceTest.java
  src/test/java/com/example/green/template/base/BaseControllerUnitTest.java
  src/test/java/com/example/green/template/request/ImageUploadRequest.java
  src/test/java/com/example/integration/file/FileServiceIntTest.java
Labels: dev:feature

#27 feat: [#18] 엑셀 파일 다운로더 기능 구현
  build.gradle
  src/main/java/com/example/green/global/excel/core/ExcelDataMapper.java
  src/main/java/com/example/green/global/excel/core/ExcelDataMapperRegistry.java
  src/main/java/com/example/green/global/excel/core/ExcelDownloader.java
  src/main/java/com/example/green/global/excel/exception/ExcelException.java
  src/main/java/com/example/green/global/excel/exception/ExcelExceptionMessage.java
  src/main/java/com/example/green/global/excel/style/BackGroundColor.java
  src/main/java/com/example/green/global/excel/style/ExcelField.java
  src/main/java/com/example/green/global/excel/style/FieldFormat.java
  src/main/java/com/example/green/infra/excel/SXSSFExcelDownloader.java
  src/test/java/com/example/green/global/excel/core/ExcelDataMapperRegistryTest.java
  src/test/java/com/example/green/global/excel/style/BackGroundColorTest.java
  src/test/java/com/example/green/global/excel/style/ExcelFieldTest.java
  src/test/java/com/example/green/global/excel/style/FieldFormatTest.java
  src/test/java/com/example/integration/common/ServiceIntegrationTest.java
  src/test/java/com/example/integration/config/TestBeanConfig.java
  src/test/java/com/example/integration/excel/ExcelDataMapperRegistryIntTest.java
  src/test/java/com/example/integration/excel/ExcelDownloaderIntTest.java
  src/test/java/com/example/integration/excel/TestDto.java
  src/test/java/com/example/integration/excel/TestExcelDataMapper.java
Labels: archi:APP, run-integration-test

#39 feat: [#39] 정보 도메인 단위테스트 및 구현체 생성
  src/main/java/com/example/green/domain/info/controller/InfoController.java
  src/main/java/com/example/green/domain/info/controller/InfoControllerDocs.java
  src/main/java/com/example/green/domain/info/controller/api/InfoResponseMessage.java
  src/main/java/com/example/green/domain/info/domain/InfoEntity.java
  src/main/java/com/example/green/domain/info/domain/vo/InfoCategory.java
  src/main/java/com/example/green/domain/info/dto/InfoListResponse.java
  src/main/java/com/example/green/domain/info/dto/InfoRequest.java
  src/main/java/com/example/green/domain/info/dto/InfoResponse.java
  src/main/java/com/example/green/domain/info/exception/InfoException.java
  src/main/java/com/example/green/domain/info/exception/InfoExceptionMessage.java
  src/main/java/com/example/green/domain/info/repository/InfoRepository.java
  src/main/java/com/example/green/domain/info/service/InfoService.java
  src/test/java/com/example/green/domain/info/domain/InfoEntityTest.java
Labels: dev:feature

#43 cicd: [#41] Swagger 경로 환경 변수 추가
  .github/workflows/deploy.yaml
Labels: archi:DevOps, run-integration-test

#48 cicd: [#41] .env 파일 따로 copy 하도록 변경
  .github/workflows/deploy.yaml
Labels: archi:DevOps, run-integration-test

#49 feat: [#32] 포인트 상품 도메인 구현
  src/main/java/com/example/green/domain/pointshop/entity/pointproduct/PointProduct.java
  src/main/java/com/example/green/domain/pointshop/entity/pointproduct/vo/BasicInfo.java
  src/main/java/com/example/green/domain/pointshop/entity/pointproduct/vo/DisplayStatus.java
  src/main/java/com/example/green/domain/pointshop/entity/pointproduct/vo/Media.java
  src/main/java/com/example/green/domain/pointshop/entity/pointproduct/vo/Price.java
  src/main/java/com/example/green/domain/pointshop/entity/pointproduct/vo/SellingStatus.java
  src/main/java/com/example/green/domain/pointshop/entity/pointproduct/vo/Stock.java
  src/main/java/com/example/green/domain/pointshop/exception/PointProductException.java
  src/main/java/com/example/green/domain/pointshop/exception/PointProductExceptionMessage.java
  src/main/java/com/example/green/global/error/exception/GlobalExceptionMessage.java
  src/main/java/com/example/green/global/utils/EntityValidator.java
  src/test/java/com/example/green/domain/pointshop/entity/pointproduct/PointProductTest.java
  src/test/java/com/example/green/domain/pointshop/entity/pointproduct/vo/BasicInfoTest.java
  src/test/java/com/example/green/domain/pointshop/entity/pointproduct/vo/MediaTest.java
  src/test/java/com/example/green/domain/pointshop/entity/pointproduct/vo/PriceTest.java
  src/test/java/com/example/green/domain/pointshop/entity/pointproduct/vo/StockTest.java
  src/test/java/com/example/green/global/utils/EntityValidatorTest.java
Labels: archi:APP

#52 refactor: [#40] 도메인단 및 DTO 코드 개선 작업
  src/main/java/com/example/green/domain/info/domain/InfoEntity.java
  src/main/java/com/example/green/domain/info/domain/vo/InfoCategory.java
  src/main/java/com/example/green/domain/info/dto/InfoExcelDto.java
  src/main/java/com/example/green/domain/info/dto/InfoListResponse.java
  src/main/java/com/example/green/domain/info/dto/InfoPage.java
  src/main/java/com/example/green/domain/info/dto/InfoRequest.java
  src/main/java/com/example/green/domain/info/dto/InfoResponse.java
  src/main/java/com/example/green/domain/info/dto/admin/InfoDetailResponseByAdmin.java
  src/main/java/com/example/green/domain/info/dto/admin/InfoSearchListResponseByAdmin.java
  src/main/java/com/example/green/domain/info/dto/admin/InfoSearchResponseByAdmin.java
  src/main/java/com/example/green/domain/info/dto/user/InfoDetailResponseByUser.java
  src/main/java/com/example/green/domain/info/dto/user/InfoSearchListResponseByUser.java
  src/main/java/com/example/green/domain/info/dto/user/InfoSearchResponseByUser.java
  src/main/java/com/example/green/domain/info/exception/InfoExceptionMessage.java
  src/main/java/com/example/green/domain/info/utils/PrefixSequenceIdGenerator.java
  src/test/java/com/example/green/domain/info/domain/InfoEntityTest.java
Labels: dev:fix, chore
