Repository GreenWiNit/backend, pull requests merged in 2025-08, with the labels that each got.

#180 [Feat/#164] 회원탈퇴 스웨거 문서화 개선
  src/main/java/com/example/green/domain/member/controller/docs/MemberControllerDocs.java
  src/main/java/com/example/green/domain/member/dto/WithdrawRequestDto.java
  src/main/java/com/example/green/domain/member/entity/enums/WithdrawReasonType.java
  src/main/java/com/example/green/domain/member/service/WithdrawService.java
  src/test/java/com/example/integration/auth/WithdrawMemberIntegrationTest.java
  src/test/java/com/example/integration/member/WithdrawMemberWithReasonIntegrationTest.java
Labels: chore

#185 fix: restore withdrawn member status when creating refresh token
  src/main/java/com/example/green/domain/auth/service/TokenService.java
  src/main/java/com/example/green/domain/member/entity/Member.java
  src/main/java/com/example/green/domain/member/repository/MemberRepository.java
  src/main/java/com/example/green/domain/member/service/MemberService.java
  src/test/java/com/example/green/domain/auth/service/TokenServiceWithdrawnMemberTest.java
  src/test/java/com/example/green/domain/member/service/MemberServiceWithdrawnRestoreTest.java
  src/test/java/com/example/integration/auth/WithdrawnMemberReSignupIntegrationTest.java
Labels: bug, run-integration-test

#199 Fix/#192
  src/main/java/com/example/green/domain/example/tools/DbInitializer.java
  src/main/java/com/example/green/domain/pointshop/order/controller/OrderController.java
  src/main/java/com/example/green/domain/pointshop/order/controller/docs/OrderControllerDocs.java
  src/main/java/com/example/green/domain/pointshop/order/controller/dto/ExchangeApplicationResult.java
  src/main/java/com/example/green/domain/pointshop/order/controller/dto/PointProductApplicantResult.java
  src/main/java/com/example/green/domain/pointshop/order/controller/dto/SingleOrderRequest.java
  src/main/java/com/example/green/domain/pointshop/order/entity/vo/MemberSnapshot.java
  src/main/java/com/example/green/domain/pointshop/order/service/OrderService.java
  src/main/java/com/example/green/domain/pointshop/order/service/command/SingleOrderCommand.java
  src/main/java/com/example/green/infra/query/order/OrderQueryRepositoryImpl.java
  src/test/java/com/example/green/domain/pointshop/order/controller/OrderControllerTest.java
  src/test/java/com/example/green/domain/pointshop/order/entity/OrderTest.java
  src/test/java/com/example/green/domain/pointshop/order/service/OrderServiceTest.java
  src/test/java/com/example/green/template/base/BaseControllerUnitTest.java
  src/test/java/com/example/integration/config/TestTokenServiceConfig.java
  src/test/java/com/example/integration/order/OrderDataSource.java
  src/test/java/com/example/integration/order/OrderIdempotencyTest.java
Labels: run-integration-test

#197 [ Feat/#195] 재가입 방지 및 사용자 조회 api
  src/main/java/com/example/green/domain/auth/OAuth2FailureHandler.java
  src/main/java/com/example/green/domain/auth/OAuth2RedirectValidator.java
  src/main/java/com/example/green/domain/auth/exception/AuthExceptionMessage.java
  src/main/java/com/example/green/domain/auth/exception/WithdrawnMemberAccessException.java
  src/main/java/com/example/green/domain/auth/resolver/CustomAuthorizationRequestResolver.java
  src/main/java/com/example/green/domain/auth/service/CustomOAuth2UserService.java
  src/main/java/com/example/green/domain/auth/service/TokenService.java
  src/main/java/com/example/green/domain/member/controller/MemberController.java
  src/main/java/com/example/green/domain/member/controller/message/MemberResponseMessage.java
  src/main/java/com/example/green/domain/member/dto/MemberInfoResponseDto.java
  src/main/java/com/example/green/domain/member/dto/WithdrawRequestDto.java
  src/main/java/com/example/green/domain/member/entity/Member.java
  src/main/java/com/example/green/domain/member/service/MemberService.java
  src/main/java/com/example/green/global/config/SecurityConfig.java
  src/test/java/com/example/green/domain/auth/service/TokenServiceWithdrawnMemberTest.java
  src/test/java/com/example/green/domain/member/service/MemberServiceWithdrawnRestoreTest.java
  src/test/java/com/example/integration/auth/WithdrawnMemberBlockingIntegrationTest.java
  src/test/java/com/example/integration/auth/WithdrawnMemberReSignupIntegrationTest.java
Labels: dev:feature, dev:fix, run-integration-test

#219 [feat: Content-Disposition 헤더를 추가]
  src/main/java/com/example/green/global/config/SecurityConfig.java
Labels: chore

#250 fix : [정보공유] PageNated 형식에 맞는 Dto로 통일 (#232)
  src/main/java/com/example/green/domain/info/controller/InfoController.java
  src/main/java/com/example/green/domain/info/controller/InfoControllerDocs.java
  src/main/java/com/example/green/domain/info/repository/InfoRepository.java
  src/main/java/com/example/green/domain/info/service/InfoService.java
  src/main/java/com/example/green/domain/info/service/InfoServiceImpl.java
  src/test/java/com/example/integration/info/InfoServiceIntTest.java
Labels: bug, run-integration-test

#252 fix : [정보공유] 전시여부 ‘미전시’ : 데이터 아예 삭제됨 (#251)
  src/main/java/com/example/green/domain/info/domain/InfoEntity.java
  src/main/java/com/example/green/domain/info/repository/InfoRepository.java
  src/main/java/com/example/green/domain/info/service/InfoServiceImpl.java
Labels: bug, run-integration-test

#262 refactor: 관리자 회원 삭제 API http method 변경
  src/main/java/com/example/green/domain/member/controller/MemberAdminController.java
  src/main/java/com/example/green/domain/member/controller/docs/MemberManagementControllerDocs.java
  src/test/java/com/example/green/domain/member/controller/MemberAdminControllerTest.java
Labels: chore

#268 [Feat/#263] 카카오 로그인 기능을 구현
  src/main/java/com/example/green/domain/auth/dto/KakaoResponseDto.java
  src/main/java/com/example/green/domain/auth/enums/OAuth2Provider.java
  src/main/resources/application.yml
Labels: dev:feature

#295 feat: CORS 설정에 Idempotency-Key 헤더를 추가
  src/main/java/com/example/green/global/config/SecurityConfig.java
Labels: chore

#322 [Hotfix/#319] #315,#316,#319 이슈 해결
  src/main/java/com/example/green/domain/auth/controller/AuthV2Controller.java
  src/main/java/com/example/green/domain/auth/controller/docs/AuthControllerDocs.java
  src/main/java/com/example/green/domain/auth/controller/docs/AuthV2ControllerDocs.java
  src/main/java/com/example/green/domain/auth/controller/message/AuthResponseMessage.java
  src/main/java/com/example/green/domain/member/controller/MemberV2Controller.java
  src/main/java/com/example/green/domain/member/controller/docs/MemberControllerDocs.java
  src/main/java/com/example/green/domain/member/controller/docs/MemberV2ControllerDocs.java
  src/main/java/com/example/green/domain/member/service/MemberService.java
  src/test/java/com/example/green/domain/member/service/MemberServiceTest.java
  src/test/java/com/example/green/domain/member/service/MemberServiceWithdrawnRestoreTest.java
  src/test/java/com/example/integration/auth/WithdrawnMemberBlockingIntegrationTest.java
Labels: bug, dev:feature, dev:fix, run-integration-test
